name: Deploy Renotech App

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build Go application
      run: |
        export GOOS=linux
        export GOARCH=amd64
        export CGO_ENABLED=0
        go build -ldflags="-s -w" -o build

    - name: Stop services
      run: |
        sudo systemctl stop renotech.service
        sudo systemctl stop cloudflared.service

    - name: Deploy application
      run: |
        cp build /opt/renotech/
        chmod +x /opt/renotech/build

    - name: Start services
      run: |
        sudo systemctl start renotech.service
        sudo systemctl start cloudflared.service

    - name: Check deployment
      run: |
        sleep 5
        sudo systemctl status renotech.service --no-pager
        sudo systemctl status cloudflared.service --no-pager
        
    - name: Test application
      run: |
        curl -f http://localhost:8000 || echo "Local test failed"
        curl -f https://renotech.space || echo "Public test failed"